frob!

diff --git a/bin/syn-signupload b/bin/syn-signupload
--- a/bin/syn-signupload
+++ b/bin/syn-signupload
@@ -1,6 +1,21 @@
 #!/bin/bash
 # Paul Tagliamonte, GPLv3, 2011
 echo "Signing uploads."
+
+if [ "x`ls *sigs`" != "x" ]; then
+	echo "Sigs already present"
+	echo "Checking if we need to resign"
+	syn-verifyupload > /dev/null 2>&1
+
+	if [ $? -ne 0 ]; then
+		rm *sigs
+		echo "invalid sig. resigning."
+	else
+		echo "valid sigs. quitting"
+		exit 1
+	fi
+fi
+
 UPLOADS=`md5sum *.syn*`
 PKG=`ls *.syn`
 echo "$UPLOADS" > $PKG.sigs
